### ISSUE TITLE
Dependencies of non-available packages

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#14]
Suppose that a user wants to `install.packages(c("pkgA", "pkgB"))` (with `bspm` enabled). Suppose that `pkgA` is provided in the system repos and has zero dependencies; `pkgB` is *not* provided in the system repos and depends on `pkgC`, which *is* available in the system repos. @eddelbuettel what would you expect?

1. `pkgA` is installed from system repos. `pkgB` and `pkgC` are installed from CRAN (current behaviour).
2. `pkgA` and `pkgC` are installed from system repos. `pkgB` is installed from CRAN.
3. (1) by default, but (2) if enabled via `options`.
4. (2) by default, but (1) if disabled via `options`.

**Comment by eddelbuettel** [comment]
I think one of the strengths of the current design is that it does _not_ reinvent `install.packages()` but dispatches to it.  So my recommendation is to keep is simple and rely as much as you can on R.  And I don't even really know what R does in the case of mixed binary and source (as I almost always rely / have relied on source).  RSPM appears to fall back to 'compiling from source' for binaries it does not have, which is twice as bad because presumably it does not have them for lack of easy building so by then calling for a build from source it sets it up for a fail in all cases I encountered so far (in Docker settings).

**Comment by Enchufa2** [comment]
I think current behaviour is ok, but I'm probably too biased because I programmed it.

Above I was specifically thinking about something like `pkgA=errors`, `pkgB=simmer`, `pkgC=Rcpp`. The call to `bspm::install_sys` would install `errors` and return `simmer`. Then R would install `Rcpp` first and then `simmer`. Option (2) above would extract `simmer` dependencies and perform a second `bspm` pass with them, and so `Rcpp` would get installed from system. Then R would see that `Rcpp` is already satisfied and install only `simmer`. But this obviously generates _other_ problems. For example, if the installation of `simmer` from source fails, then the user gets `Rcpp` anyway (this is a bad example, because `Rcpp` would be for sure useful for _many_ other packages, but you get the point).

I was considering (3) if your expectations differed _a bit_ and (2) or (4) only if they differed _a lot_ with my (probably biased) expectations. But if not, it's ok as it is.
