### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by Enchufa2** [Enchufa2/bspm#2]
Not sure how for some parts.

**Comment by Enchufa2** [comment]
@eddelbuettel: A quick note regarding this. I added some minimal tests that are [checked via GA on Fedora and Debian](https://github.com/Enchufa2/bspm/blob/master/.github/workflows/build.yml). However, I had to add [this](https://github.com/Enchufa2/bspm/blob/master/inst/tinytest/test_manager.R#L16) because it wasn't present in `.libPaths()` on Debian (neither on Ubuntu, rocker/r-base or rocker/r-ver). Is this intentional, or maybe a mistake?

**Comment by eddelbuettel** [comment]
I have not sure what you are doing there (i.e. where your R comes from).  A Debian or Debian-based system using R via a binary built from my package has a triple `.libPaths()`, and always had it since an evening in a Vienna bar maybe 17 years ago where Kurt and Fritz made the suggestion (to split R 'recommend / base' packages off into `/usr/lib/R/site-library`) and the remainning local ones into `/usr/local/lib/R/site-library` as the distributions had always done already.

With that packaged content from the distribution *always* goes into `/usr`.  User-managed, or third party content, *always* goes to `/usr/loca/lib/R/site-library` and I *very strongly* recommend you think twice about mixing `/usr` and `/usr/local`.  It. Is. Not. A. Good. Idea. To. Mix.

```sh
edd@rob:~$ docker run --rm -ti r-base Rscript -e '.libPaths()'        # Debian unstable/testing "inside"
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
[3] "/usr/lib/R/library"           
edd@rob:~$ Rscript -e '.libPaths()'                                   # Ubuntu 20.04
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"       "/usr/lib/R/library"           
edd@rob:~$ 
```

And in what I have done so far for `bspm` I kept that split as there is no reason not to:

```
edd@rob:~$ docker run --rm -ti rocker/r-rspm:20.04 Rscript -e '.libPaths()'
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"      
[3] "/usr/lib/R/library"           
edd@rob:~$ 
```

I made that one Ubuntu-based to be more easily comparable to the `r-rspm` using RSPM.  

Happy to help but have to catch up on a few work items now.

**Comment by Enchufa2** [comment]
What I mean is that

```bash
$ docker run --rm -it rocker/r-ver:latest Rscript -e '.libPaths()'
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"
```

But packages from apt are installed under `/usr/lib/R/site-library`. So when I install something with `bspm` from the system repos, the R session doesn't pick it up.

**Comment by eddelbuettel** [comment]
Well well well -- that is not my container, but one made by Carl and Noam, and, as of recently, also changed, and it does NOT use the binary I refer to above,  So it is different for that reason.  FWIW I don't generally work off `r-ver` myself.

It is also a _very_ specific set of containers.  Why would you need `r-ver` for BSPM?

**Comment by eddelbuettel** [comment]
And actually:

> But packages from apt are installed under /usr/lib/R/site-library. So when I install something with bspm from the system repos, the R session doesn't pick it up.

Documentation from `r-ver` tells you *explicitly* not to do that.  `r-ver` is about date and version pinning via MRAN (v1) and now RSPM.  

So yes, you did start with the wrong container / are using that container the wrong way which explains the ugly hack.  I recommend changing containers.

**Comment by Enchufa2** [comment]
Ok, I see.

> It is also a _very_ specific set of containers. Why would you need `r-ver` for BSPM?

For CI testing. At first, I thought about testing a matrix the functionality on a matrix of R versions using r-ver. Then I thought it's not worth it, because the two things I use from base R, `install.packages` and `trace`, are not expected to change. Certainly they are not different now under different R versions. So I switched to testing based on the latest Fedora and Debian docker images: install R, install python3-(dnf|apt), install tinytest from CRAN and check the package.

But without adding that line highlighted above it was failing in base Debian and Ubuntu too... Strange. Forget about it. I'll have to check again.

**Comment by eddelbuettel** [comment]
Ah well.  You could also have asked me for help as I already told you days ago I had a container.

But hey you broke it you get all the glory of glueing it all back together. :grin:

**Comment by Enchufa2** [comment]
Got it. Found the issue I was experimenting in Debian, Ubuntu and rocker/r-base: it's `--as-cran`! That flag removes `site-library` stuff from the paths. Didn't know that. :roll_eyes:

**Comment by eddelbuettel** [comment]
Ah, yes.  

Actually, for testing `--as-cran`, R creates a new temporary .libPaths() containing only the base R packages AND the declared packages from DESCRIPTION so that it can identify any possibly omitted packages.
