### ISSUE TITLE
bspm on arch linux

### ISSUE THREAD

**Issue by mihem** [Enchufa2/bspm#34]
Thanks for this great package @Enchufa2 . If you have many packages and regularly update them, you spend quite some time on compilation, so this is great.

bspm works like a charm on my Ubuntu server. However, on my local computer I use Arch Linux and I struggle with the installation. There is `python-pacman` which could be equivalent to `python3-apt` ? After enabling `bspm::enable()` using `sudo R`, `install.packages("xgboost")` yet fails with `Error: cannot connect to the system package manager`.

Is there a working solution on Arch?

Thank you!
Mischko

**Comment by Enchufa2** [comment]
Hi, thanks for bringing this up. I did take a look some time ago, but I'm not that familiar with Arch myself and I couldn't figure out what are the possibilities there. Basically we need two components to make this work:

1. Are there any repositories of pre-compiled R packages for Arch? I saw that there are many AURs, but from what I understood, AUR only stores the recipes to build the packages, but it is not a build system and does not provide the binaries. So whenever an end-user adds one of these repos and tries to install a package, it is compiled locally, which is of little to no help in the case of R packages.
2. In case we have 1., then we need to connect to pacman. We do this by calling the Python bindings of the corresponding package manager. For instance, dnf relies on the libdnf library, which has Python bindings called python3-dnf. Similarly, we have apt -> libapt -> python3-apt. So we would need to figure out what are these for pacman -> ? -> ?.

**Comment by mihem** [comment]
Thanks for the quick response.
Oh, I am afraid this exceeds my knowledge, but what I found out.

1. There are quite some R packages in the AUR, starting with `r-`, e.g. by this maintainer `https://aur.archlinux.org/packages/?K=dviktor&SeB=m&O=200`. But you are right, when I install e.g. `Rcpp`  using pacman, it starts compiling.
2.  I have never used it, but based on the documentation the package that I mentioned `python-pacman` https://github.com/peakwinter/python-pacman should be suitable?

**Comment by Enchufa2** [comment]
I found [this](https://man.archlinux.org/man/libalpm.3.en), which suggests that we have pacman -> libalpm -> [pyalpm](https://pyalpm.readthedocs.io/en/latest/?badge=latest). So we could look into the integration of pyalpm into bspm, but then this is useless if no binary repositories exist.

One possibility may be using [OBS](https://build.opensuse.org/), which supports generating binaries for many (all?) distributions. This is one thing we have in the radar, but I haven't found the time yet to play with OBS. Maybe you could try pinging the maintainer(s) of this AUR you mentioned, maybe they are interested in using OBS to provide pre-compiled binaries. Then, we could work out the pacman integration.

**Comment by mihem** [comment]
I mailed the maintainer as you suggested.
Thanks.

**Comment by dvdesolve** [comment]
hello! I'm a maintainer of 254 R packages and a co-maintainer of 46 R packages in AUR, 300 in total.

I have free resources to host binary compiled R packages as an Arch repository on my server. Unfortunately I have no experience with your tool for installing binary R packages and I want to know if it will be possible to use Arch binary repository for such needs.

If there will be demand on compiled versions I can start to populate my repository step by step. As of now I only maintain (and co-maintain) just most popular versions, however, I can add extra ones on request.

What do you think?

**Comment by eddelbuettel** [comment]
Please see what @Enchufa2 wrote above, we need some domain knowledge for Arch.  Otherwise background is in our [arXiv paper](https://arxiv.org/abs/2103.08069) -- and you can play with the [Rocker Project containers](https://hub.docker.com/r/rocker/r-bspm/tags) that have `bspm` enabled to just how it works under Ubuntu or Fedora.

In short, we probably just need a day's work (and some testing) to enable system manager integration. After that it gets better with more binaries.  Ubuntu has over 5k, Fedora and OpenSuSE have ~17k.  All contributed by volunteers like you.

**Comment by dvdesolve** [comment]
Unfortunately I'm not a developer of pacman and/or Arch, but I think @eli-schwartz can help there a bit

**Comment by Enchufa2** [comment]
@dvdesolve Starting from a minimal Arch base (e.g., a docker image), could you provide detailed instructions (i.e., for an Arch newbie) on how to install R, enable your repo and install a binary version of a package (e.g., Rcpp) using pacman? I can take it from there to try to integrate ALPM into bspm.

**Comment by dvdesolve** [comment]
Yes, of course. But I need to create some bootstrapping repository first. I'll ping you here as it will be done

**Comment by dvdesolve** [comment]
Well, I think I have something to start. As for now I've created small repository on my server which have ggplot2 with all dependencies in place. URL: https://desolve.ru/archrepo/x86_64

**Comment by dvdesolve** [comment]
Now it contains about 132 compiled packages! Also want to notice that I'm gradually moving AUR stuff [to a new repo](https://github.com/dvdesolve/ArchRPkgs). Please feel free to help with population, updates etc

**Comment by dvdesolve** [comment]
> @dvdesolve Starting from a minimal Arch base (e.g., a docker image), could you provide detailed instructions (i.e., for an Arch newbie) on how to install R, enable your repo and install a binary version of a package (e.g., Rcpp) using pacman? I can take it from there to try to integrate ALPM into bspm.

Installation guide is very well described [here](https://wiki.archlinux.org/title/Installation_guide).

To enable my binary repo you can use instructions in [this repo](https://github.com/dvdesolve/ArchRPkgs) or simply add to your `/etc/pacman.conf` these lines:
```
[desolve]
Server = https://desolve.ru/archrepo/$arch
```
Please note that only `x86_64` packages are built for now, but the addition of `i686` and different ARMs may be the question of near future. Also you can add my public GPG key if you want checking of signatures of my packages:
```
# pacman-key --recv-keys DD3BF75DCD96541AC723B7CD6A4CD3276CA8EBBD
# pacman-key --lsign-key DD3BF75DCD96541AC723B7CD6A4CD3276CA8EBBD
```
Otherwise you should add `SigLevel = Optional` option to the definition of my repository

**Comment by Enchufa2** [comment]
Great, I'll try it as soon as I find some time.

**Comment by Enchufa2** [comment]
So far, I managed to install/uninstall arch packages using pyalpm as follows:

```python3
import pycman
import pyalpm

pkgs = ["r-ggplot2"]

args = pycman.action_sync.parse_options([])
handle = pycman.config.init_with_config_and_options(args)
repos = dict((db.name, db) for db in handle.get_syncdbs())

targets = []
for name in pkgs:
    ok, pkg = pycman.action_sync.find_sync_package(name, repos)
    #pkg = handle.get_localdb().get_pkg(name)
    if type(pkg) is pyalpm.Package:
        targets.append(pkg)

if len(targets):
    t = pycman.transaction.init_from_options(handle, args)
    for pkg in targets:
        t.add_pkg(pkg)
        #t.remove_pkg(pkg)
    ok = pycman.transaction.finalize(t)
```

But the progress output is awful. Is there any way to obtain a nicer output, similar to `pacman -S r-ggplot2`? /cc @eli-schwartz

**Comment by dvdesolve** [comment]
@Enchufa2 can you please provide screenshot or so?

**Comment by Enchufa2** [comment]
You can check it yourself. Here's a reproducible example using the official docker image:

```bash
$ docker run --rm -it archlinux
# pacman -Sy
# pacman -S r pyalpm git
# git clone -b feature/alpm https://github.com/Enchufa2/bspm.git
# R CMD INSTALL bspm
# cat >> /etc/pacman.conf << EOF
[desolve]
Server = https://desolve.ru/archrepo/\$arch
EOF
# Rscript -e 'bspm::install_sys("Rcpp")'
```

**Comment by Enchufa2** [comment]
@mihem @dvdesolve The `feature/alpm` branch above (PR candidate in #35) now contains a version with a nicer output, although quite restrained, with no fancy progress bars (PRs welcome for that). Please try that branch in your Arch box (note that, in a desktop/server setting, you'll need to install `python-{dbus,gobject}` too; see the updated [installation instructions](https://github.com/Enchufa2/bspm/blob/39b3c8695f05466de070fc54ec9afa6f68188814/README.md#arch)). You can also try the `feature/alpm-default` branch to see the default output (the awful one).

If you confirm it works for you, I'll merge #35 and submit a new release to CRAN (no hurries, because CRAN submissions are closed until January 4).

**Comment by Enchufa2** [comment]
@mihem @dvdesolve Did you have the chance to give #35 a try?

**Comment by mihem** [comment]
@Enchufa2 thanks so much, great news. I am sorry, I actually switched from arch linux to ubuntu a few weeks ago (one of the main reasons being the better integration of R packages thanks to Dirk an others).

**Comment by dvdesolve** [comment]
Thank you for your efforts! I think we'll provide `bspm` as separate binary package in our repo

**Comment by Enchufa2** [comment]
Thanks, v0.3.9 submitted to CRAN.
