### ISSUE TITLE
Case insensitivity in package names

### ISSUE THREAD

**Issue by dkutner** [Enchufa2/bspm#65]
I (probably foolishly) have my own package called `Projections`. When I try to install it using `bspm`, it installs the `projections` package binary whose source is hosted by CRAN, rather than my package with a capitalized name. I'm not sure if this is avoidable given debian's lowercase package name requirement.

**Comment by eddelbuettel** [comment]
You may be out of luck there is the genral rules is `paste("r", repo, tolower(pkg), sep="-")`.

**Comment by eddelbuettel** [comment]
And I was just riffing about this with a friend: CRAN imposes case-insensitivity because some OSs cannot do case-sensitivity.  So one cannot distinguish package directories.

**Comment by Enchufa2** [comment]
I'm sorry but, due to the reasons that Dirk pointed out, your package name is basically taken. And even if this wasn't the case and all platforms supported case sensitivity, I don't think it would be a good idea. Projections, projections, proJections, projecTIONS... etc. This would only confuse users.
