### ISSUE TITLE
Provide GitHub action

### ISSUE THREAD

**Issue by flying-sheep** [Enchufa2/bspm#74]
Would be great to have a GitHub action that sets up bspm together with a cache like [awalsh128/cache-apt-pkgs-action](https://github.com/awalsh128/cache-apt-pkgs-action). I dream of sth. simple like:

```yaml
jobs:
  test:
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: Enchufa2/setup-bspm@v1
    - uses: r-lib/actions/setup-r-dependencies@v2
```

where `r-lib/actions/setup-r-dependencies` would take like 30 seconds on first run (installing binary dependencies) and 1 second with warm cache (installing the same binary dependencies from cache)

**Comment by Enchufa2** [comment]
Thanks for the suggestion! I'll investigate further, but in principle I see several drawbacks. First and foremost, bspm installs system packages that are tied to a system R installation. Therefore, a bspm action wouldn't be compatible with r-lib's setup-r. Another friction point is that bspm alone doesn't work until you define a system repository containing R packages. This is distro-dependent, and in the same distro, there may be several options (such as Michael's [c2d4u](https://launchpad.net/~c2d4u.team/+archive/ubuntu/c2d4u4.0+) and Dirk's [r2u](https://github.com/eddelbuettel/r2u)).

For this reason alone, I think that it's easier from the user's standpoint to just spin a docker container with everything set up such as my [r-copr](https://github.com/Enchufa2/cran2copr/pkgs/container/r-copr) (based on Fedora) or [r2u](https://github.com/rocker-org/r2u) (based on Ubuntu). Or even just to run a script that sets everything up (the Dockerfile for r2u is a good starting point).

On top of that, I think that the action that you link above would do the trick.

**Comment by flying-sheep** [comment]
> bspm installs system packages that are tied to a system R installation

Ah, that makes sense of course! But there should be a way to get this functionality with few lines of configuration. :thinking:

**Comment by eddelbuettel** [comment]
See [r-ci](https://eddelbuettel.github.io/r-ci) which is set up the way it is as I value the portability.  You could turn it 90 degrees and create an action from it.

**Comment by Enchufa2** [comment]
> See [r-ci](https://eddelbuettel.github.io/r-ci) which is set up the way it is as I value the portability. You could turn it 90 degrees and create an action from it.

This is good stuff. @flying-sheep The script above covers 90% of what you are looking for. The cache part is a bit more tricky, and definitely outside of the scope of this repo, because it's package manager-dependent. I'm no expert in APT, but I'd say that applying GH's [cache](https://github.com/actions/cache) action to the (1) package database (wherever it is), and (2) the R package library, you should be good to go.

**Comment by flying-sheep** [comment]
I’m mostly happy to check it out. “mostly” because I’m not a huge fan of shell scripts:

1. shell syntax is unmaintainable and error prone. (too many landmines and boilerplate: `set -euxo pipefail`, `read -r` instead of `$()`, …)
2. the region folding syntax individual CI solutions is useful and it’s unlikely commands have those built in (although a CI specific command might surprise me here)
3. CI system specific steps can have outputs, and parsing env variables or files instead is a huge pain

apart from item 1, there can be solutions, but they’re rarely there.

**Comment by Enchufa2** [comment]
Well... YAML files are great but they do not do anything on their own; so most workflows are, behind the scenes, just 
a bunch of shell scripts. ;-)

FWIW, [r-ci](https://eddelbuettel.github.io/r-ci/) is prepared so that you can consume it easily in your YAML. From the example there, you basically (1) curl it and bootstrap the environment in one step, (2) then install the dependencies in another step, (3) then run tests (or whatever) in another step of your YAML.

On the other hand, I'm a big fan of just using containers for CI, and as I was saying, there are already containers out there with R + bspm (+ the proper repos) preinstalled. For instance, [this](https://github.com/Enchufa2/bspm/blob/e4dc3404bf04d8b7eb9c23f8584665116a34f4a1/.github/workflows/build.yml#L62-L75) is how I check that new versions of bspm would behave _in the wild_ using the r2u image.

It should be more or less straightforward to add a cache action to that workflow. But currently the effort doesn't pay off, at least for me, for saving just a few seconds (compared to the binary installations themselves, which save us _minutes_).

**Comment by Enchufa2** [comment]
That said, let me recap this thread for future me. _It would be possible_ to provide a GA that would behave as follows, but the are some open issues:

1. Detect the OS. It should be one of the supported Linux distribution.
    - What would happen if the OS is not supported? E.g. a Windows or a macOS runner.
    - The action would not be compatible with `r-lib/actions/setup-r`. What would happen if such action was run before?
2. Install a repo with R packages compatible with (1) (configurable parameter).
3. Install the proper version of R according to (2).
    - For most systems, this means the official R package for that distribution, but some repos may require adding _another repo_ with a specific version of R, so another parameter for this would be required.
4. Install bspm according to (1 and 2).
5. (Optional) Set up a cache for R and packages.

Issues apart, steps 1-4 are more or less clear, but 5 is more complicated, and I think that it would be best to have a _separate_ generic action capable of caching _any_ system package. Then, a YAML file may look like this:

```yaml
jobs:
  test:
    steps:
    - uses: actions/checkout@v3
    - name: Setup R + bspm
      uses: Enchufa2/actions/setup-r-bspm@v1
    - name: Install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
    - name: Cache packages
      uses: <somebody>/actions/cache-system@v1
```

But it's a lot of work, especially because I'm not proficient enough in GA development (beyond setting and reusing YAMLs), and there are already a number of solutions out there. So I'm closing this for now as "not planned", but will reopen in the future if I learn more about GA and I see a clear (and reasonable) path forward. Thanks again.

**Comment by flying-sheep** [comment]
> On the other hand, I'm a big fan of just using containers for CI

I like containers, but I think GitHub actions have a nice hybrid of “batteries included” (little helpers like jq) and composability. Makes it a bit easier to set up a multi language environment than other CI environments, and much easier than writing one’s own Dockerfile. As said: The only real problem I have is the lack of binary R packages on Linux, and that’s a R ecosystem problem, not a problem with GitHub actions.

> For instance, [this](https://github.com/Enchufa2/bspm/blob/e4dc3404bf04d8b7eb9c23f8584665116a34f4a1/.github/workflows/build.yml#L62-L75) is how I check that new versions of bspm would behave in the wild using the r2u image.

I think if some care has been taken so those containers aren’t too different from the basic GH “ubuntu-latest”, that

> most workflows are, behind the scenes, just a bunch of shell scripts. ;-)

I’m OK with shell scripts as long as they have no logic. The `if:` being some simple CI system specific grammar isn’t ideal, but vastly better than a 40 years old pile of bespoke shell subtleties.

<details>
<summary>Optional rant, reader discretion is advised</summary>

I’ve spent too much time to learn good shell practice in the last 15 years and I don’t trust myself to write a correct shell script. I haven’t seen a single shell script fulfilling my safety standards in the wild. Therefore I don’t trust anyone to write a correct shell script. (Sorry Dirk. Maybe your added 20 years of experience suddenly make it click and one is effortlesly able to avoid the myriad of ways to subtly not do what one intended, but I somehow doubt it)

Not every shell script will blow up and do something wildly different than expected, but it’s so so much more that do it than in languages that only ignore errors when explicitly asked. I really hope Nushell takes off, until then I’ll write scripts in Python and CLIs in Python or Rust.

</details>

**Comment by eddelbuettel** [comment]
> The only real problem I have is the lack of binary R packages on Linux

Nice trolling.

**Comment by flying-sheep** [comment]
> Nice trolling

What’s with that accusation? Don’t assume malice where there is absolutely none intended. I’m saddened that you default to such a jaded reaction and hope you can soon find joy again in interacting with the wider open source community:

I’m not very involved in the R community anymore, I’m just dipping in to maintain a Python<->R data science conversion package. I don’t know much that’s going on. I simply referred to the that CRAN hosts macOS and Windows binary packages but not Linux binary packages, and am searching for a solution for my CI jobs.

I’m very grateful to all the other people who work to make my life easier (just like I work to make theirs easier).

I don’t understand why you think I’m trolling in any way, shape, or form.

**Comment by eddelbuettel** [comment]
If you were actually capable of reading I would (once again) point you to two working solutions for your "problem".  But we already gave them to you, yet you still run around like a three-year old crying for his ice cream.  That's trolling.

Hint:  Working solution to your "problem" are in multiple answer in this thread.  I"ll unsubsribe now as I am wasting time I could use on real work.

**Comment by flying-sheep** [comment]
I was very polite even after you accused me the first time, and now you just escalate? I really expected more of a community figure like you. 

I have read, I have my solution. My motivations for the comment after locking the thread were:
- respond to the role of containers for CI (limitations thereof)
- shed light on how an incoming/outgoing cache system ideally works since @Enchufa2 implied it wasn’t fully clear to them
- add a jokey paragraph about the messy reality of shell scripting, while collapsing it so only people who are up for something like that get confronted with it.

You on the other hand first accuse me of being insincere, then double down with more abuse. Why are you like that.

@Enchufa2 can you please lock this thread so Dirk doesn’t continue insulting people?
